
Movie Recommendation System

Import ML Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity 
from sklearn.feature_extraction.text import CountVectorizer

Load the Data 

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving movies_dataset.csv to movies_dataset.csv


Store all Data

In [ ]:
df = pd.read_csv('movies_dataset.csv')
df.head(3)

budget  ... Unnamed: 20
0  237000000  ...         NaN
1  300000000  ...         NaN
2  245000000  ...         NaN

[3 rows x 21 columns]

Get Count of the number of rows(Movies) in the data set and the number of columns

In [ ]:
df.shape

(504, 21)

Created a list of important columns(head) for the recommendation engine which is must important to define separetely.

In [ ]:
columns = ['overview','genres','original_title']
df[columns].head(5)

overview  ...                            original_title
0  In the 22nd century, a paraplegic Marine is di...  ...                                    Avatar
1  Captain Barbossa, long believed to be dead, ha...  ...  Pirates of the Caribbean: At World's End
2  A cryptic message from Bond’s past sends him o...  ...                                   Spectre
3  Following the death of District Attorney Harve...  ...                     The Dark Knight Rises
4  John Carter is a war-weary, former military ca...  ...                               John Carter

[5 rows x 3 columns]

Check for missing values in the columns(heads)

In [ ]:
df[columns].isnull().values.any()

False

Create a function to combine the values of the important columns into a single string

In [ ]:
def get_important_features(data):
  important_features =  []
  for i in range(0, data.shape[0]):
    important_features.append(str(data['overview'][i])+' '+str(data['genres'][i])+' '+str(data['original_title'][i])) 

  return important_features  

Create a Column to hold the combined strings

In [ ]:
df['important_features'] = get_important_features(df)
df.head(3)

budget  ...                                 important_features
0  237000000  ...  In the 22nd century, a paraplegic Marine is di...
1  300000000  ...  Captain Barbossa, long believed to be dead, ha...
2  245000000  ...  A cryptic message from Bond’s past sends him o...

[3 rows x 22 columns]

Convert the text to a matrix of token counts 

In [ ]:
cm = CountVectorizer().fit_transform(df['important_features'])

Get the cosine similarity matrix from the count matrix

In [ ]:
cs = cosine_similarity(cm)
print(cs)

[[1.         0.57725089 0.51426536 ... 0.43084829 0.39840954 0.53012821]
 [0.57725089 1.         0.53441927 ... 0.47143793 0.45735108 0.54560238]
 [0.51426536 0.53441927 1.         ... 0.40815592 0.38686132 0.45891316]
 ...
 [0.43084829 0.47143793 0.40815592 ... 1.         0.50491862 0.45747997]
 [0.39840954 0.45735108 0.38686132 ... 0.50491862 1.         0.43971349]
 [0.53012821 0.54560238 0.45891316 ... 0.45747997 0.43971349 1.        ]]


Get the shape of the cosine similarity matrix

In [ ]:
cs.shape

(504, 504)

Get the title of the movie that the user likes and find movie id's

In [ ]:
i_title = 'Avatar'
movie_id = df[df.original_title == i_title]['id'].values[0]

Create a list of enumerations for the similarity score [(movie_id, similarity_score),(.........)]

In [ ]:
scores = list(enumerate(cs[movie_id]))

Sort the list

In [ ]:
sorted_scores = sorted(scores, key = lambda x:x[1], reverse = True)
sorted_scores = sorted_scores[1:]
print(sorted_scores)

[(61, 0.7134437307504793), (322, 0.6837634587578276), (232, 0.6666834337261043), (33, 0.6454738786573266), (168, 0.6424675480244509), (72, 0.6384997577922866), (31, 0.6383106423916778), (122, 0.6348603145949657), (104, 0.6326266278117371), (267, 0.6297282423460627), (187, 0.6264306159840216), (490, 0.6252412661738194), (196, 0.6230559828490335), (198, 0.6225317562548817), (300, 0.6208806662893214), (452, 0.6208004980885296), (152, 0.6173419725817378), (305, 0.6153871128820448), (112, 0.6148170459575759), (200, 0.6146889990862595), (151, 0.6126374746329802), (46, 0.6124007462959206), (131, 0.6122670268929316), (370, 0.6112009239889423), (88, 0.6073032226993986), (275, 0.6071582289507228), (485, 0.6070850460322766), (495, 0.6068614929872402), (138, 0.6065414277162509), (167, 0.6065403172605964), (96, 0.6044944448335207), (68, 0.6038073644245601), (123, 0.6008449768853287), (243, 0.5990967368408634), (459, 0.5977387946809766), (483, 0.5976143046671969), (487, 0.5976143046671968), (410, 0.

Create a loop to print the first 7 similar movies

In [ ]:
j = 0
print('The Most recommended movie to', i_title, 'are:\n')
for item in sorted_scores:
  movie_title = df[df.id == item[0]]['original_title'].values[0]
  print(j+1, movie_title)
  j = j+1
  if j>6:
    break

The Most recommended movie to Avatar are:

1 Jupiter Ascending
2 The Adventures of Pluto Nash
3 Monsters, Inc.
4 X-Men: The Last Stand
5 Final Fantasy: The Spirits Within
6 Suicide Squad
7 Iron Man 3
